# Generated by Django 5.2.4 on 2025-09-07 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(db_column='ID_prenotazione', primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(db_column='data_prenotazione', null=True)),
            ],
            options={
                'db_table': 'PRENOTAZIONE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_column='data_inizio')),
                ('end_date', models.DateField(db_column='data_fine')),
            ],
            options={
                'db_table': 'DETTAGLI_PRENOTAZIONE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_column='username', max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=255, null=True)),
                ('email', models.CharField(db_column='email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'UTENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeRoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_column='ruolo', max_length=32)),
                ('start_date', models.DateField(db_column='data_inizio')),
                ('end_date', models.DateField(db_column='data_fine', null=True)),
            ],
            options={
                'db_table': 'DIPENDENTE_RUOLO_STORICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('hosting_date', models.DateField(db_column='data_ospitazione', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OSPITA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cf', models.CharField(db_column='CF', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=50, null=True)),
                ('surname', models.CharField(db_column='cognome', max_length=50, null=True)),
                ('phone', models.CharField(db_column='telefono', max_length=20, null=True)),
                ('city', models.CharField(db_column='citta', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PERSONA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(db_column='ID_recensione', primary_key=True, serialize=False)),
                ('service_type', models.CharField(db_column='tipo_servizio', max_length=32)),
                ('vote', models.IntegerField(db_column='voto')),
                ('description', models.TextField(db_column='descrizione')),
                ('review_date', models.DateTimeField(db_column='data_recensione', null=True)),
            ],
            options={
                'db_table': 'RECENSIONE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(db_column='ID_servizio', primary_key=True, serialize=False)),
                ('price', models.DecimalField(db_column='prezzo', decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(db_column='tipo_servizio', max_length=32)),
                ('status', models.CharField(db_column='status', default='DISPONIBILE', max_length=15)),
            ],
            options={
                'db_table': 'SERVIZIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(db_column='ID_turno', primary_key=True, serialize=False)),
                ('day', models.CharField(db_column='giorno', max_length=10, null=True)),
                ('start_hour', models.TimeField(db_column='ora_inizio', null=True)),
                ('end_hour', models.TimeField(db_column='ora_fine', null=True)),
                ('description', models.CharField(db_column='descrizione', max_length=100, null=True)),
            ],
            options={
                'db_table': 'TURNO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('hire_date', models.DateField(db_column='data_assunzione', null=True)),
                ('termination_date', models.DateField(db_column='data_licenziamento', null=True)),
            ],
            options={
                'db_table': 'DIPENDENTE',
                'managed': False,
            },
        ),
    ]
