# Generated by Django 5.2.4 on 2025-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('CF', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'PERSONA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ruolo', models.CharField(max_length=50)),
                ('data_assunzione', models.DateField()),
                ('data_licenziamento', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'DIPENDENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('CF', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'UTENTE',
                'managed': False,
            },
        ),
    ]
