# Generated by Django 5.2.4 on 2025-09-07 16:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalActivity',
            fields=[
                ('id', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.service')),
                ('activity_code', models.CharField(db_column='cod_attivita', max_length=3, unique=True)),
                ('description', models.TextField(db_column='descrizione')),
            ],
            options={
                'verbose_name': 'Attività con animali',
                'verbose_name_plural': 'Attività con animali',
                'db_table': 'ATTIVITA_CON_ANIMALI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Composizione pacchetto',
                'verbose_name_plural': 'Composizioni pacchetto',
                'db_table': 'COMPOSTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_date', models.DateTimeField(db_column='data_iscrizione', null=True)),
                ('participants', models.IntegerField(db_column='partecipanti', default=1)),
            ],
            options={
                'verbose_name': 'Iscrizione',
                'verbose_name_plural': 'Iscrizioni',
                'db_table': 'iscrive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(db_column='ID_evento', primary_key=True, serialize=False)),
                ('seats', models.IntegerField(db_column='posti')),
                ('title', models.CharField(db_column='titolo', max_length=100)),
                ('description', models.TextField(db_column='descrizione')),
                ('date', models.DateField(db_column='data_evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'db_table': 'EVENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID_ordine', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='data', null=True)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'db_table': 'ORDINE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='quantita')),
                ('unit_price', models.DecimalField(db_column='prezzo_unitario', decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Dettaglio ordine',
                'verbose_name_plural': 'Dettagli ordine',
                'db_table': 'DETTAGLIO_ORDINE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(db_column='ID_pacchetto', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=32)),
                ('description', models.TextField(db_column='descrizione')),
            ],
            options={
                'verbose_name': 'Pacchetto',
                'verbose_name_plural': 'Pacchetti',
                'db_table': 'PACCHETTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_column='data_inizio')),
            ],
            options={
                'verbose_name': 'Assegnazione turno',
                'verbose_name_plural': 'Assegnazioni turno',
                'db_table': 'SVOLGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.service')),
                ('playground_code', models.CharField(db_column='cod_campo', max_length=3, unique=True)),
                ('max_capacity', models.PositiveIntegerField(db_column='max_capienza', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Campo da gioco',
                'verbose_name_plural': 'Campi da gioco',
                'db_table': 'CAMPO_DA_GIOCO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.service')),
                ('sunbed_code', models.CharField(db_column='cod_lettino', max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Piscina',
                'verbose_name_plural': 'Piscine',
                'db_table': 'PISCINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='ID_prodotto', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=100)),
                ('price', models.DecimalField(db_column='prezzo', decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'db_table': 'PRODOTTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(db_column='data_acquisto', null=True)),
            ],
            options={
                'verbose_name': 'Acquisto',
                'verbose_name_plural': 'Acquisti',
                'db_table': 'ACQUISTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.service')),
                ('table_code', models.CharField(db_column='cod_tavolo', max_length=3, unique=True)),
                ('max_capacity', models.PositiveIntegerField(db_column='max_capienza', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Ristorante',
                'verbose_name_plural': 'Ristoranti',
                'db_table': 'RISTORANTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.service')),
                ('room_code', models.CharField(db_column='cod_camera', max_length=3, unique=True)),
                ('max_capacity', models.PositiveIntegerField(db_column='max_capienza', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Camere',
                'db_table': 'CAMERA',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': False, 'verbose_name': 'Prenotazione', 'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='bookingdetail',
            options={'managed': False, 'verbose_name': 'Dettaglio prenotazione', 'verbose_name_plural': 'Dettagli prenotazione'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'verbose_name': 'Dipendente', 'verbose_name_plural': 'Dipendenti'},
        ),
        migrations.AlterModelOptions(
            name='employeerolehistory',
            options={'managed': False, 'verbose_name': 'Ruolo storico dipendente', 'verbose_name_plural': 'Ruoli storici dipendenti'},
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'managed': False, 'verbose_name': 'Ospitazione', 'verbose_name_plural': 'Ospitazioni'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'verbose_name': 'Persona', 'verbose_name_plural': 'Persone'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False, 'verbose_name': 'Recensione', 'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'verbose_name': 'Servizio', 'verbose_name_plural': 'Servizi'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'managed': False, 'verbose_name': 'Turno', 'verbose_name_plural': 'Turni'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.AlterModelTable(
            name='bookingdetail',
            table='DETTAGLIO_PRENOTAZIONE',
        ),
    ]
