# Generated by Django 5.2.4 on 2025-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partecipanti', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'ISCRIVE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('ID_evento', models.AutoField(primary_key=True, serialize=False)),
                ('posti', models.IntegerField()),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('data_evento', models.DateField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'EVENTO',
                'managed': False,
            },
        ),
    ]
