# Generated by Django 5.2.4 on 2025-09-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enrollmodel_eventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServizioModel',
            fields=[
                ('ID_servizio', models.AutoField(primary_key=True, serialize=False)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_servizio', models.CharField(choices=[('CAMERA', 'Camera'), ('PISCINA', 'Piscina'), ('RISTORANTE', 'Ristorante'), ('CAMPO_DA_GIOCO', 'Campo da Gioco'), ('ATTIVITA_CON_ANIMALI', 'Attività con Animali')], max_length=50)),
                ('status', models.CharField(choices=[('DISPONIBILE', 'Disponibile'), ('OCCUPATO', 'Occupato'), ('MANUTENZIONE', 'Manutenzione')], default='DISPONIBILE', max_length=20)),
            ],
            options={
                'db_table': 'SERVIZIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttivitaConAnimaliModel',
            fields=[
                ('ID_servizio', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.serviziomodel')),
                ('cod_attivita', models.CharField(max_length=10)),
                ('descrizione', models.TextField()),
            ],
            options={
                'db_table': 'ATTIVITA_CON_ANIMALI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('ID_servizio', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.serviziomodel')),
                ('cod_camera', models.CharField(max_length=10)),
                ('max_capienza', models.IntegerField()),
            ],
            options={
                'db_table': 'CAMERA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampoDaGiocoModel',
            fields=[
                ('ID_servizio', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.serviziomodel')),
                ('cod_campo', models.CharField(max_length=10)),
                ('max_capienza', models.IntegerField()),
            ],
            options={
                'db_table': 'CAMPO_DA_GIOCO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PiscinaModel',
            fields=[
                ('ID_servizio', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.serviziomodel')),
                ('cod_lettino', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'PISCINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RistoranteModel',
            fields=[
                ('ID_servizio', models.OneToOneField(db_column='ID_servizio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.serviziomodel')),
                ('cod_tavolo', models.CharField(max_length=10)),
                ('max_capienza', models.IntegerField()),
            ],
            options={
                'db_table': 'RISTORANTE',
                'managed': False,
            },
        ),
    ]
